### ISSUE TITLE
Error: fatal: could not read Username for 'https://gitlab.example.com': No such device or address

### ISSUE THREAD

**Issue by illagrenan** [sourcebot-dev/sourcebot#60]
This is my configuration for my self-hosted Gitlab instance:

```json
{
  "$schema": "https://raw.githubusercontent.com/sourcebot-dev/sourcebot/main/schemas/v2/index.json",
  "repos": [
    {
      "type": "gitlab",
      "url": "https://gitlab.example.com",
      "token": {
        "env": "GITLAB_TOKEN"
      },
      "revisions": {
        "branches": [
          "main",
          "master"
        ]
      },
      "groups": [
        "foo",
        "bar"
      ],
      "projects": [
        "baz/foo"
      ],
      "exclude": {
        "archived": true,
        "forks": true
      }
    }
  ]
}
```
In my log, I see a lot of these errors. No repo is synchronizing.

``` console
2024-11-07 13:54:40 [backend] |     at Object.action (file:///app/node_modules/simple-git/dist/esm/index.js:4462:25)
2024-11-07 13:54:40 [backend] |     at PluginStore.exec (file:///app/node_modules/simple-git/dist/esm/index.js:4501:25)
2024-11-07 13:54:40 [backend] |     at file:///app/node_modules/simple-git/dist/esm/index.js:1369:43
2024-11-07 13:54:40 [backend] |     at new Promise (<anonymous>)
2024-11-07 13:54:40 [backend] |     at GitExecutorChain.handleTaskData (file:///app/node_modules/simple-git/dist/esm/index.js:1367:16)
2024-11-07 13:54:40 [backend] |     at GitExecutorChain.<anonymous> (file:///app/node_modules/simple-git/dist/esm/index.js:1351:44)
2024-11-07 13:54:40 [backend] |     at Generator.next (<anonymous>)
2024-11-07 13:54:40 [backend] |     at fulfilled (file:///app/node_modules/simple-git/dist/esm/index.js:45:24)
2024-11-07 13:54:40 [backend] |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-07 13:54:40 [backend] | 2024-11-07T12:54:40.104Z info: [main] Fetching gitlab.example.com/libs/styx...
2024-11-07 13:54:40 [backend] | 2024-11-07T12:54:40.178Z error: [main] fatal: could not read Username for 'https:// gitlab.example.com': No such device or address
2024-11-07 13:54:40 [backend] | 
2024-11-07 13:54:40 [backend] | Error: fatal: could not read Username for 'https://gitlab.example.com': No such device or address
```

My GitLab Personal access token is valid and has these permissions: read_api, read_user, read_repository. I have tried the latest version `v2.4.0`; the latest version that works for me is `v2.0.2`. What might be the issue? Do you have any ideas?

**Comment by brendan-kellam** [comment]
Heya - do you mind sending along more of the logs? I see there is an exception being thrown, but it's not obvious where it's being thrown.

**Comment by illagrenan** [comment]
Yesterday I was debugging this; I deleted the whole Docker volume with data, and today I can't replicate the problem again. Maybe it was a problem with the subsequent upgrades; I started with the same volume from the very first release of Sourcebot 🤷 

If it happens again, I'll let you know. Thanks!

**Comment by brendan-kellam** [comment]
Interesting - yea I could see it being a symptom of migrating from v1 to v2. Glad to hear it is fixed!
