### ISSUE TITLE
TypeError: a.toSorted is not a function

### ISSUE THREAD

**Issue by er0k** [sourcebot-dev/sourcebot#77]
I am getting this error trying out the new v2.4.2 container:

```
2024-11-18T17:10:43.761Z info: [main] Discovered 637 unique repositories from config.
2024-11-18T17:10:43.761Z error: [main] Failed to sync configuration file /data/conifg.json with error:
TypeError: a.toSorted is not a function
    at arraysEqualShallow (file:///app/packages/backend/dist/utils.js:72:23)
    at isRevisionsChanged (file:///app/packages/backend/dist/main.js:64:18)
    at isRepoReindxingRequired (file:///app/packages/backend/dist/main.js:76:13)
    at syncConfig (file:///app/packages/backend/dist/main.js:143:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async measure (file:///app/packages/backend/dist/utils.js:5:18)
    at async _syncConfig (file:///app/packages/backend/dist/main.js:191:36)
    at async main (file:///app/packages/backend/dist/main.js:226:5)

```

This doesn't occur in the v2.4.1 container.

**Comment by brendan-kellam** [comment]
Will take a look, thanks for the report

**Comment by brendan-kellam** [comment]
Ah yep this is my bad - I introduced a [Array.prototype.toSorted](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted) call [here](https://github.com/sourcebot-dev/sourcebot/pull/65/files#diff-0a4dad0de53ac89bf5e11c09599ddd67988124be80650d00e2d115f9125905c7R78), but it's only supported in NodeJs versions 20+ (the docker container is on 18).

I will update the node version of the container to 20

**Comment by brendan-kellam** [comment]
Kk was able to repro - bumping the version does resolve the issue. Just released [v2.4.3](https://github.com/sourcebot-dev/sourcebot/releases/tag/v2.4.3). Just waiting on this [GitHub action](https://github.com/sourcebot-dev/sourcebot/actions/runs/11899966697) to be done

**Comment by er0k** [comment]
Just confirmed the error is gone in the v2.4.3 container. Thanks for the quick fix! 🚀

**Comment by brendan-kellam** [comment]
Great!
